// Lista de jugadores del plantel — formato "Apellido, Nombre", orden alfabético
export const PLAYERS: string[] = [
  "Accinelli, Gianluca",
  "Alvarez Sly, Fernando",
  "Barberis, Joaquín",
  "Barzola, Ignacio",
  "Barzola, Juan Martin",
  "Battipede, Octavio",
  "Blanco, Lucas",
  "Camiño, Bautista",
  "Campana, Fernando",
  "Campana, Guillermo",
  "Campana, Juan Pablo",
  "Carregal, Agustín",
  "Carreño, Joaquín",
  "Casanova, Agustín",
  "Cavalieri, Santino",
  "Celichini, Tomás",
  "Cocina, Fausto",
  "Crovetto, Jorge",
  "Druetta, Felipe",
  "Encina, Tobias",
  "Erriquenz, Juan Pablo",
  "Fernández, Santiago",
  "Iarusso, Mateo",
  "Lajmanovich, Lauraro",
  "Lascano, Manuel",
  "Lascano, Martín",
  "López Lado, Rodrigo",
  "Matías, Bautista",
  "Moauro, Gianluca",
  "Montero, Juan",
  "Nacach, Agustín",
  "Ponce, Julian",
  "Rossi, Enzo",
  "Salas, Pedro",
  "Solari, Matias",
  "Sotero Sávori, Tomás",
  "Suarez, Felipe",
]
