// Lista de jugadores del plantel — formato "Apellido, Nombre", orden alfabético
export const PLAYERS: string[] = [
  "Accinelli, Gianluca",
  "Aguiar, Franco Nicolás",
  "Alvarez Sly, Fernando",
  "Barberis, Joaquín",
  "Barzola, Ignacio",
  "Barzola, Juan Martin",
  "Blanco, Lucas",
  "Camiño, Bautista",
  "Campana, Fernando",
  "Campana, Guillermo",
  "Campana, Juan Pablo",
  "Carregal, Agustín",
  "Carreño, Joaquín",
  "Casanova, Agustín",
  "Cavalieri, Santino",
  "Celichini, Tomás",
  "Cocina, Fausto",
  "Díaz, Santiago",
  "Druetta, Felipe",
  "Encina, Tobias",
  "Fernández, Santiago",
  "Iarusso, Mateo",
  "Lajmanovich, Lauraro",
  "Lascano, Manuel",
  "Lascano, Martín",
  "López Lado, Rodrigo",
  "Matías, Bautista",
  "Moauro, Gianluca",
  "Montero, Juan",
  "Nacach, Agustín",
  "Rossi, Enzo",
  "Salerno Picasso, Lorenzo",
  "Santoro, Franco",
  "Sotero Sávori, Tomás",
  "Suarez, Felipe",
  "Ugarte, Joaquín",
]
